# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies early for better caching
COPY package*.json ./
RUN npm install

# Copy rest of the app files
COPY . .

# Expose the default NestJS port
EXPOSE 3000

# Start the app in development mode with hot-reloading
CMD ["npm", "run", "start:dev"]
